version: '3.8'
services:
  db:
    image: mysql:8.0.30
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

backend:
  build:
    context: ./backend
    dockerfile: Dockerfile
  command: bash -c "rm -f yasai_pocket/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  volumes:
    - ./backend:/yasai_pocket
    - ./backend/vendor/bundle:/yasai_pocket/vendor/bundle
  environment:
    TZ: Asia/Tokyo
  ports:
    - '3001:3000'
  depends_on:
    - db
  stdin_open: true
  tty: true
