name: frontend Lint and Test

on:
  push:
    paths:
      - "frontend/**"

jobs:
  eslint_prettier:
    name: ESlint and Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "frontend/package.json"
      - name: Run yarn install
        run: yarn install
      - name: Run lint
        run: yarn run lint
      - name: Run format
        run: yarn run format
